# Custom dataset config reusing the HM3D loader but pointing at my360 data.

defaults:
  - view_sampler: bounded

name: hm3d
roots: [/srv/store/docker-users/thesis/marten1/data/my360_dataset_pt]
rgb_roots: [/srv/store/docker-users/thesis/marten1/data/my360_dataset]
make_baseline_1: false
augment: true

image_shape: [512, 1024]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

baseline_epsilon: 1e-3
max_fov: 100.0

skip_bad_shape: true
near: 0.1
far: 10.0
baseline_scale_bounds: false
shuffle_val: false
test_len: -1
test_chunk_interval: 1
test_times_per_scene: 1
stage_dirs:
  train: train
  val: train
  test: train
enable_val: false
